"""add file hash to images

Revision ID: 2c6dda7a33d1
Revises: 7e4671380e48
Create Date: 2024-11-20 21:10:37.517973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c6dda7a33d1'
down_revision: Union[str, None] = '7e4671380e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_images_file_hash'), 'images', ['file_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_file_hash'), table_name='images')
    op.drop_column('images', 'file_hash')
    # ### end Alembic commands ###
