"""Add created_at and updated_at to images

Revision ID: 4341a6fa326b
Revises: 63531a8609e7
Create Date: 2024-07-19 12:43:57.535388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4341a6fa326b'
down_revision: Union[str, None] = '63531a8609e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('images', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'updated_at')
    op.drop_column('images', 'created_at')
    # ### end Alembic commands ###
