"""Remove slug from images - it will be autogenerated

Revision ID: 669c1f65dbaf
Revises: 3bebbfa39e6b
Create Date: 2024-07-29 01:48:38.780745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "669c1f65dbaf"
down_revision: Union[str, None] = "3bebbfa39e6b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_images_slug", table_name="images")
    op.drop_column("images", "slug")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("images", sa.Column("slug", mysql.VARCHAR(length=100), nullable=True))
    op.create_index("ix_images_slug", "images", ["slug"], unique=True)
    # ### end Alembic commands ###
