"""Add slug field to Image model

Revision ID: 8842824e0b93
Revises: 7e4671380e48
Create Date: 2024-10-28 23:27:59.311971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8842824e0b93'
down_revision: Union[str, None] = '7e4671380e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('slug', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_images_slug'), 'images', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_slug'), table_name='images')
    op.drop_column('images', 'slug')
    # ### end Alembic commands ###
