"""Add gallery_image association table

Revision ID: c90baf1fe0c1
Revises: 07f9763630a3
Create Date: 2024-07-18 20:08:18.741395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "c90baf1fe0c1"
down_revision: Union[str, None] = "07f9763630a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gallery_image",
        sa.Column("gallery_id", sa.Integer(), nullable=True),
        sa.Column("image_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["gallery_id"],
            ["galleries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["images.id"],
        ),
    )
    op.drop_constraint("images_ibfk_1", "images", type_="foreignkey")
    op.drop_column("images", "gallery_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "images",
        sa.Column(
            "gallery_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key(
        "images_ibfk_1", "images", "galleries", ["gallery_id"], ["id"]
    )
    op.drop_table("gallery_image")
    # ### end Alembic commands ###
